services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: ct648
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_db
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app-network

  backend:
    image: oven/bun:latest
    working_dir: /app
    environment:
      VITE_DATABASE_URL: postgres://postgres:12345678@database:5432/ct648
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    command: sh -c "bun install && bun run dev"
    depends_on:
      - database
    networks:
      - app-network

  frontend:
    image: oven/bun:latest
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    environment:
      VITE_BACKEND_URL: http://localhost:3000/graphql
    command: sh -c "bun install && bun run vite --host"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:
  pgadmin-data:

networks:
  app-network:
    driver: bridge
