services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tetris_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_db
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app-network

  backend:
    image: oven/bun:latest
    working_dir: /app
    environment:
      DATABASE_URL: postgres://admin:admin@database:5432/tetris_db
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    command: sh -c "bun install && bun run dev"
    depends_on:
      - database
    networks:
      - app-network

  frontend:
    image: oven/bun:latest
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      - ฺBACKEND_URL=http://ec2-3-7-254-26.ap-south-1.compute.amazonaws.com:3000/graphql
    ports:
      - "5173:5173"
    command: sh -c "bun install && bun run vite --host"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:
  pgadmin-data:

networks:
  app-network:
    driver: bridge
